[phases.setup]
nixPkgs = ["php82", "php82Extensions.intl"]

[phases.install]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader"
]

[start]
cmd = "php spark serve --host=0.0.0.0 --port=$PORT"
