[variables]
NIXPACKS_PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.intl",
  "php82Extensions.mbstring",
  "php82Extensions.zip",
  "php82Extensions.opcache"
]

[phases.install]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
